import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import postcss from "postcss";

const serviceRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(serviceRoot, "src", "styles.source.css");
const outputPath = path.join(serviceRoot, "src", "styles.css");
const scope = ".publish-queue-runner";

function isInsideKeyframes(rule) {
  let parent = rule.parent;
  while (parent) {
    if (parent.type === "atrule" && /keyframes$/i.test(parent.name)) return true;
    parent = parent.parent;
  }
  return false;
}

function scopedSelector(selector) {
  const trimmed = selector.trim();
  if (trimmed === "*") return `${scope}, ${scope} *`;
  if (trimmed.startsWith(scope)) return trimmed;
  if (/^:root\b/.test(trimmed)) return trimmed.replace(/^:root\b/, scope);
  if (/^html\s+body\b/.test(trimmed)) return trimmed.replace(/^html\s+body\b/, scope);
  if (/^body\b/.test(trimmed)) return trimmed.replace(/^body\b/, scope);
  if (/^html\b/.test(trimmed)) return trimmed.replace(/^html\b/, scope);
  return `${scope} ${trimmed}`;
}

const scopePlugin = {
  postcssPlugin: "scope-publish-queue-runner",
  Rule(rule) {
    if (isInsideKeyframes(rule)) return;
    rule.selector = rule.selectors.map(scopedSelector).join(",\n");
  },
};

const source = await readFile(sourcePath, "utf8");
const result = await postcss([scopePlugin]).process(source, {
  from: sourcePath,
  to: outputPath,
});

await writeFile(
  outputPath,
  `/* Generated by scripts/scope-css.mjs; edit styles.source.css instead. */\n${result.css}`,
  "utf8",
);
